"""initial schema

Revision ID: 731d2d1c8ccf
Revises: 
Create Date: 2026-08-22 16:54:51.275981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '731d2d1c8ccf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('contaminant_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('candidate_causes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nodes',
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('breadth_m', sa.Float(), nullable=False),
    sa.Column('invert_level_m', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('node_id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('contaminant_id', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trigger_type', sa.String(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.node_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_node_id', sa.String(), nullable=False),
    sa.Column('child_node_id', sa.String(), nullable=False),
    sa.Column('length_m', sa.Float(), nullable=False),
    sa.Column('manning_n', sa.Float(), nullable=False),
    sa.Column('slope', sa.Float(), nullable=False),
    sa.Column('tau_base_s', sa.Float(), nullable=False),
    sa.Column('validated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['child_node_id'], ['nodes.node_id'], ),
    sa.ForeignKeyConstraint(['parent_node_id'], ['nodes.node_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_node_id', 'child_node_id', name='uq_edge_parent_child')
    )
    op.create_table('incident_nodes',
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.node_id'], ),
    sa.PrimaryKeyConstraint('incident_id', 'node_id')
    )
    op.create_table('model_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('contaminant_id', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('pushed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('acked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('running', sa.Boolean(), nullable=False),
    sa.Column('shadow_disagreement_rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.node_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_health_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('contaminant_id', sa.String(), nullable=False),
    sa.Column('health_state', sa.String(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.node_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('summary_windows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('t_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('t_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('level_m', sa.Float(), nullable=False),
    sa.Column('speed_mps', sa.Float(), nullable=False),
    sa.Column('q_m3s', sa.Float(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.node_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id', 'seq', name='uq_summary_node_seq')
    )
    op.create_index('ix_summary_node_tend', 'summary_windows', ['node_id', 't_end'], unique=False)
    op.create_table('contaminant_readings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('summary_id', sa.UUID(), nullable=False),
    sa.Column('contaminant_id', sa.String(), nullable=False),
    sa.Column('mean', sa.Float(), nullable=False),
    sa.Column('max', sa.Float(), nullable=False),
    sa.Column('median', sa.Float(), nullable=False),
    sa.Column('std', sa.Float(), nullable=True),
    sa.Column('flux_g_s', sa.Float(), nullable=True),
    sa.Column('mass_g', sa.Float(), nullable=True),
    sa.Column('t_max', sa.DateTime(timezone=True), nullable=True),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('sensor_health', sa.String(), nullable=False),
    sa.Column('rule_state', sa.String(), nullable=False),
    sa.Column('ml_anomaly', sa.Float(), nullable=True),
    sa.Column('final_state', sa.String(), nullable=False),
    sa.Column('model_ver', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['summary_id'], ['summary_windows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reading_contaminant', 'contaminant_readings', ['contaminant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reading_contaminant', table_name='contaminant_readings')
    op.drop_table('contaminant_readings')
    op.drop_index('ix_summary_node_tend', table_name='summary_windows')
    op.drop_table('summary_windows')
    op.drop_table('sensor_health_events')
    op.drop_table('model_versions')
    op.drop_table('incident_nodes')
    op.drop_table('edges')
    op.drop_table('alerts')
    op.drop_table('nodes')
    op.drop_table('incidents')
    # ### end Alembic commands ###
