"""add incident window bounds

Revision ID: beae7abd92c5
Revises: 731d2d1c8ccf
Create Date: 2026-08-22 19:04:00.009366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beae7abd92c5'
down_revision: Union[str, None] = '731d2d1c8ccf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('window_t_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('incidents', sa.Column('window_t_end', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'window_t_end')
    op.drop_column('incidents', 'window_t_start')
    # ### end Alembic commands ###
